/* eslint-disable camelcase */
import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'
import '../styles/globals.css'
import { Header } from '@/components/Header'

const ibm_plex_sans = IBM_Plex_Sans({
  weight: ['700', '400'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={ibm_plex_sans.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
